apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
  namespace: ns1
  labels:
    app-name: kuard
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    ports:
    - containerPort: 8080
    name: kuard-container
  