apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: ns1
  labels: 
    app-name: kuard
spec:
  # nodeSelector:
  #   nodeSubnetType: public # pod does not need to be in public, service do
  containers:
  - name: kuard-app
    image: gcr.io/kuar-demo/kuard-amd64:blue  # apps runs on port 8080
    ports: 
    - containerPort: 8080  # port which the container exposes (both in container and pod)
      # hostPort: 5000 # host's (node) external-ip port where the container is mapped to; use this to expose the pod on the hosting node itself without going through Service.
  # restartPolicy:
  
  


  # where does the pod get deployed?
    # network
    # node ip
    # pod cluster ip / port
    # can we access it?

  # workload failure - contract for the pod running
    # how do we define pod is working?
    # custom probing

