# maps IAM role to Kubernetes user/group
# maps IAM user to Kubernetes user/group
# CANNOT map IAM group to Kubernetes user/group

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::848808798256:role/clusterAdminRole
      username: cluster-admin:{{SessionName}}
      groups:
        - system:masters
    - rolearn: arn:aws:iam::848808798256:role/clusterUserRole
      username: cluster-user:{{SessionName}}
      groups:
        - cluster-user-group
    - rolearn: arn:aws:iam::848808798256:role/clusterViewerRole
      username: cluster-viewer:{{SessionName}}
      groups:
        - cluster-viewer-group
    - rolearn: arn:aws:iam::848808798256:role/ns0AdminRole
      username: ns0-admin:{{SessionName}}
      groups:
        - cluster-viewer-group
        - ns0-admin-group
    - rolearn: arn:aws:iam::848808798256:role/ns0UserRole
      username: ns0-user:{{SessionName}}
      groups:
        - cluster-viewer-group
        - ns0-user-group
    - rolearn: arn:aws:iam::848808798256:role/myEksNodeServiceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes