apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  labels:
    name: kuard
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: ns1
  labels: 
    app-name: kuard
spec:
  # nodeSelector:
  # restartPolicy:
  containers:
  - name: kuard-app
    image: gcr.io/kuar-demo/kuard-amd64:blue
    ports: 
    - containerPort: 80
      hostPort: 8080
      # hostIP: