apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns1-viewer-role
  namespace: ns1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: 
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns1-viewer-rolebinding
roleRef:
  kind: Role
  name: ns1-viewer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: ns1-viewer-group
  apiGroup: rbac.authorization.k8s.io