apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns1-admin-role
  namespace: ns1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns1-admin-rolebinding
roleRef:
  kind: Role
  name: ns1-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: ns1-admin-group
  apiGroup: rbac.authorization.k8s.io